### ISSUE TITLE
Bert Base模型性能测试脚本启动不起来

### ISSUE THREAD

**Issue by Aurelius84** [Oneflow-Inc/DLPerf#103]
我复现单机单卡下Bert Base FP32的性能，遇到脚本一直提示我`LoadServer`失败：
日志信息：
```
Log file created at: 2020/12/01 02:57:51
Running on machine: cb48a14bb95c
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1201 02:57:51.346987  5030 global.h:32] NewGlobal 14cudaDeviceProp
I1201 02:57:51.846197  5030 global.h:32] NewGlobal N7oneflow7EnvDescE
I1201 02:57:51.846268  5030 global.h:32] NewGlobal N7oneflow10CtrlServerE
I1201 02:57:51.849647  5030 ctrl_server.cpp:53] CtrlServer listening on 0.0.0.0:49851
I1201 02:57:51.849778  5030 global.h:32] NewGlobal N7oneflow10CtrlClientE
I1201 02:57:52.290592  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 0 times
I1201 02:58:02.290933  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 1 times
I1201 02:58:12.291249  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 2 times
I1201 02:58:22.291574  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 3 times
I1201 02:58:32.291877  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 4 times
I1201 02:58:42.292199  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 5 times
I1201 02:58:52.292503  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 6 times
I1201 02:59:02.292829  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 7 times
I1201 02:59:12.293128  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 8 times
I1201 02:59:22.293431  5030 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 9 times
```
+ 数据集：README.md中提供的
+ OneFlow版本：`oneflow-cu110     0.2.0`
+ CUDA版本：CUDA 11
+ 启动环境：docker容器中，未映射外部端口
+ 使用脚本： [bert_base_pretrain.sh](https://github.com/Oneflow-Inc/DLPerf/blob/master/OneFlow/scripts/bert_base_pretrain.sh) ，内容修改如下：
```bash
NUM_NODES=${1:-1}
GPU_NUM_PER_NODE=${2:-1}
BSZ_PER_DEVICE=${3:-32} 

BENCH_ROOT=/workspace/Bert-benchmark/OneFlow-Benchmark/LanguageModeling/BERT
DATA_ROOT=./wiki_ofrecord_seq_len_128_example
DATA_PART_NUM=1

if [ -n "$4" ]; then
    NODE_IPS=$4
else
    NODE_IPS='10.11.0.2','10.11.0.3','10.11.0.4','10.11.0.5'
fi
NODE_IPS=""

rm -rf ./log
mkdir ./log

export PYTHONUNBUFFERED=1
python3 $BENCH_ROOT/run_pretraining.py \
  --gpu_num_per_node=$GPU_NUM_PER_NODE \
  --num_nodes=$NUM_NODES \
  --node_ips=$NODE_IPS \
  --learning_rate=1e-4 \
  --batch_size_per_device=$BSZ_PER_DEVICE \
  --iter_num=140 \
  --loss_print_every_n_iter=20 \
  --seq_length=128 \
  --max_predictions_per_seq=20 \
  --num_hidden_layers=12 \
  --num_attention_heads=12 \
  --max_position_embeddings=512 \
  --type_vocab_size=2 \
  --vocab_size=30522 \
  --attention_probs_dropout_prob=0.1 \
  --hidden_dropout_prob=0.1 \
  --hidden_size_per_head=64 \
  --data_dir=$DATA_ROOT \
  --data_part_num=$DATA_PART_NUM \
  --log_dir=./log \
  --model_save_every_n_iter=10000 \
  --save_last_snapshot=False \
  --model_save_dir=./snapshots
```

跪求大佬解答~~

**Comment by chengtbf** [comment]
看log信息是grpc连接本地 localhost:49851 端口超时。

有可能是./bashrc 的代理设置问题？
看看你有没有设置类似
```shell
export http_proxy=xxx
export HTTP_PROXY=xxx
```
小写换成大写；或者关掉代理试试。

**Comment by Flowingsun007** [comment]
您好，看样子是端口连接问题，是不是设置了网络代理？可以在脚本运行前尝试用命令：
```shell
unset all_proxy && unset ALL_PROXY 
```
看看是否可以

**Comment by Aurelius84** [comment]
@Flowingsun007 @chengtbf 多谢解答，确实是我设置了`http_proxy`变量导致的，unset之后可以了。

另外，最新的oneflow-benchmark的Bert代码，在oneflow=0.2.0下`flow.optimizer.AdamW`接口有个`loss_scale_policy`参数版本兼容性问题。我在0.2.0版本下，注释掉这个参数后，方可以运行。
```python
def CreateOptimizer(args):
    warmup_batches = int(args.iter_num * args.warmup_proportion)
    lr_warmup = flow.optimizer.warmup.linear(warmup_batches, 0)
    lr_scheduler = flow.optimizer.PolynomialSchduler(args.learning_rate, args.iter_num, 0.0,
                                                     warmup=lr_warmup)
    loss_scale_policy = None
    if args.use_fp16:
        loss_scale_policy = flow.optimizer.loss_scale.dynamic_loss_scale(increment_period=2000);
    return flow.optimizer.AdamW(lr_scheduler, epsilon=1e-6, weight_decay=args.weight_decay_rate,
                                weight_decay_excludes=["bias", "LayerNorm", "layer_norm"],
                                grad_clipping=flow.optimizer.grad_clipping.by_global_norm(1.0))
                                # loss_scale_policy=loss_scale_policy)  # 这一行要在0.2.0版本注释掉才行
```

**Comment by Flowingsun007** [comment]
我们最近确实在优化和迭代，会有一些api改动和版本问题。我们会更加注意前后兼容以及在报错信息中给出友好的提示信息，感谢反馈：）

**Comment by chengtbf** [comment]
oneflow-benchmark的master分支的脚本是跟oneflow的master分支同步的。  如果想用oneflow v0.2.0，可以使用对应版本的oneflow-benchmark分支： https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/v0.2.0

**Comment by Aurelius84** [comment]
了解了，万分感谢~~

**Comment by sywang0111** [comment]
我在多机环境下也遇到了类似的报错信息,但是我并没有设置代理，`unset all_proxy && unset ALL_PROXY` 试过也不能解决问题。
Oneflow: 0.3.1
Oneflow-benchmark: master LanguageModeling/BERT
启动环境：docker --net=host
CUDA: 10.0
报错信息：
`Log file created at: 2020/12/24 15:33:47
Running on machine: gpu11
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1224 15:33:47.120837 234641 global.h:36] NewGlobal 14cudaDeviceProp
I1224 15:33:48.920328 234641 global.h:36] NewGlobal N7oneflow7EnvDescE
I1224 15:33:48.920436 234641 global.h:36] NewGlobal N7oneflow10CtrlServerE
I1224 15:33:48.922204 234641 ctrl_server.cpp:53] CtrlServer listening on 0.0.0.0:50051
I1224 15:33:48.922338 234641 global.h:36] NewGlobal N7oneflow10CtrlClientE
I1224 15:33:48.925384 234641 ctrl_client.cpp:231] LoadServer gpu11 Successful at 0 times
I1224 15:33:48.927119 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 0 times error_code 14 error_message DNS resolution failed
I1224 15:33:58.927628 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 1 times error_code 14 error_message DNS resolution failed
I1224 15:34:08.928238 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 2 times error_code 14 error_message DNS resolution failed
I1224 15:34:18.928788 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 3 times error_code 14 error_message DNS resolution failed
I1224 15:34:28.929384 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 4 times error_code 14 error_message DNS resolution failed
I1224 15:34:38.929823 234641 ctrl_client.cpp:234] LoadServer  gpu9 Failed at 5 times error_code 14 error_message DNS resolution failed`
我使用的脚本：
`python3 run_pretraining.py \
  --num_nodes=2 \
  --gpu_num_per_node=1 \
  --node_ips="gpu11, gpu9" \
  --loss_print_every_n_iter=10 \
  --iter_num=100 \
  --learning_rate=3e-5 \
  --batch_size_per_device=1 \
  --iter_num=100 \
  --seq_length=128 \
  --max_predictions_per_seq=20 \
  --num_hidden_layers=12 \
  --num_attention_heads=12 \
  --max_position_embeddings=512 \
  --type_vocab_size=2 \
  --vocab_size=30522 \
  --attention_probs_dropout_prob=0.0 \
  --hidden_dropout_prob=0.0 \
  --hidden_size_per_head=64 \
  --data_dir=./dataset/ \
  --data_part_num=2 \
  --log_dir=./bert_regresssioin_test/of \
  --model_save_dir=./bert_regresssioin_test/of \
  --save_last_snapshot False `
主要改动num_nodes=2, data_part_num=2
@chengtbf @Flowingsun007

**Comment by doombeaker** [comment]
> 我在多机环境下也遇到了类似的报错信息,但是我并没有设置代理...

你设置了多机 `--num_nodes=2`，但是没有对应的设置节点（机器）的信息，需要用以下格式设置机器信息：
```shell
--node_num=2 --node_list="192.168.1.12,192.168.1.14"
```
`192.168.1.12` 和 `192.168.1.14` 应该换成你测试的真实IP，逗号后不要有空格。
要确保机器之间可以免密ssh互通。

另外，如果 `data_part_num=2`，就要确定数据集文件数目不小于2.

bert 启动脚本的参数解释见[这里](https://docs.oneflow.org/adv_examples/bert.html)
数据集的准备见[这里](https://docs.oneflow.org/extended_topics/how_to_make_ofdataset.html#ofrecord_2)

**Comment by sywang0111** [comment]
多谢，我是用--node_ips="gpu9,gpu11"来设置节点信息的。
确实是因为我在分隔节点的逗号后多加了一个空格导致的，把空格删除就可以正常运行了。
