### ISSUE TITLE
Wrong node_rank for multinodes in the distributed bash code

### ISSUE THREAD

**Issue by slyviacassell** [Oneflow-Inc/DLPerf#113]
Hi, I find that maybe your distributed bash scripts specify a wrong value for `node_rank`.
This [code](https://github.com/Oneflow-Inc/DLPerf/blob/552ea0c8c36082f373cb6c192289dbbb1d25ec5e/NVIDIADeepLearningExamples/PyTorch/BERT/scripts/single_node_train.sh#L108) may be wrong for launching the pytorch distributed training program. The `node_rank` would be different for each node. But I find that your multinodes [bash script](https://github.com/Oneflow-Inc/DLPerf/blob/master/NVIDIADeepLearningExamples/PyTorch/BERT/scripts/run_two_nodes.sh) does not change it.

```bash
CMD="python3 -m torch.distributed.launch --nproc_per_node=$num_gpus --nnodes $num_nodes --node_rank=0  --master_addr=$master_node  --master_port=$master_port $CMD"
```

**Comment by nlqq** [comment]
Yep, if you use multi-node training, the `node_rank` is different for the specific node, and I illustrate to change this in the [README.md](https://github.com/Oneflow-Inc/DLPerf/tree/master/NVIDIADeepLearningExamples/PyTorch/resnet50v1.5)
![image](https://user-images.githubusercontent.com/20068892/104553451-9e2f6280-5675-11eb-82d9-7578918631cc.png)
It needs you to modify manually, but I can add this parameter into the bash scripts, then you can modify this argument by scripts.

**Comment by slyviacassell** [comment]
Oww, my fault. I will close this issue. Thank you for your prompt reply!

**Comment by nlqq** [comment]
Thank you for using my scripts~ Any questions are welcome~
