### ISSUE TITLE
Horovod环境

### ISSUE THREAD

**Issue by weizaixl** [Oneflow-Inc/DLPerf#92]
Horovod建议在GPU集群里安装nv_peer_memory驱动，以使用GPUDirect的能力，不知道在测试的时候有没有安装？

**Comment by Flowingsun007** [comment]
> Horovod建议在GPU容量里安装nv_peer_memory驱动，以使用GPUDirect的能力，不知道在测试的时候有没有安装？

您好，这个驱动在我们测试的物理机上都是装了的，测试NVIDIA的部分框架时（NGC的docker容器）我们发现多机加速比较低，所以后来也都加装了这个驱动。

**Comment by yuanms2** [comment]
请 @Flowingsun007 确认一下

**Comment by Flowingsun007** [comment]
> Horovod建议在GPU集群里安装nv_peer_memory驱动，以使用GPUDirect的能力，不知道在测试的时候有没有安装？

您好，我确认了一下测试环境上的物理机和NGC的容器里都是没有装nv_peer_memory的，当我尝试在物理机上安装时，遇到了和[issues/77](https://github.com/Mellanox/nv_peer_memory/issues/77)一样的报错信息，如果有任何解决办法，请和我联系，感谢！
